# Generated by Django 4.1.2 on 2022-10-15 18:27

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('memedb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meme',
            name='description',
        ),
        migrations.RemoveField(
            model_name='meme',
            name='tags',
        ),
        migrations.AddField(
            model_name='meme',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
