# Generated by Django 4.1.2 on 2022-10-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memedb', '0002_remove_meme_description_remove_meme_tags_meme_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='comparison_hash',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
